# Generated by Django 4.2 on 2023-04-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_topic_author_remove_topic_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['text']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
